"""
generate_deploy_prd — Agent Zero Tool
======================================
Analyzes a repo and generates a Markdown PRD with checkbox tasks
for the 11-step deployment pipeline.

Tool args:
    repo_url:  GitHub repository URL or local path
    app_name:  (optional) Override app name
    branch:    (optional) Git branch (default: main)
    db:        (optional) "true" to force database provisioning
    domain:    (optional) Custom domain
"""

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add project root + agent root for imports
PROJECT_ROOT = Path(__file__).resolve().parents[3]
_AGENT_ROOT = Path(__file__).resolve().parents[1]  # agents/deployment-agent/
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(_AGENT_ROOT))

from python.helpers.tool import Tool, Response
from lib.analyzer import analyze_github_repo, analyze_local_dir


class GenerateDeployPrd(Tool):

    async def execute(self, **kwargs) -> Response:
        repo_url = self.args.get("repo_url", "").strip()
        app_name = self.args.get("app_name", "").strip()
        branch = self.args.get("branch", "main").strip()
        force_db = self.args.get("db", "").lower() == "true"
        domain = self.args.get("domain", "").strip()

        if not repo_url:
            return Response(
                message="Error: repo_url is required. Provide a GitHub URL or local path.",
                break_loop=False,
            )

        # ── Step 1: Analyze ──────────────────────────────────
        if repo_url.startswith("http") or repo_url.startswith("git@"):
            analysis = analyze_github_repo(repo_url)
        elif os.path.isdir(repo_url):
            analysis = analyze_local_dir(repo_url)
        else:
            analysis = analyze_github_repo(repo_url)

        # Derive app name
        if not app_name:
            match = re.search(r"/([^/]+?)(?:\.git)?$", repo_url)
            app_name = match.group(1).lower() if match else "my-app"
            app_name = re.sub(r"[^a-z0-9-]", "-", app_name)

        project_type = analysis["type"]
        port = analysis["port"]
        needs_db = force_db or analysis["needs_db"]
        has_dockerfile = analysis["has_dockerfile"]
        env_vars = analysis.get("env_vars_needed", [])

        # Domain
        if not domain:
            domain = f"http://{app_name}.31.220.58.212.sslip.io"
        elif not domain.startswith("http"):
            domain = f"https://{domain}"

        # ── Step 2: Generate PRD ─────────────────────────────
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        prd = f"""# Deployment PRD — {app_name}

> Auto-generated by Agent Claw DeployOps on {timestamp}
> Methodology: Ralphy Loop (task → build → test → fix → next)

## Project Analysis
| Field | Value |
|-------|-------|
| Repository | {repo_url} |
| Branch | {branch} |
| App Name | {app_name} |
| Type | {project_type} |
| Language | {analysis['language']} |
| Port | {port} |
| Needs DB | {'Yes' if needs_db else 'No'} |
| Has Dockerfile | {'Yes' if has_dockerfile else 'No'} |
| Domain | {domain} |
| Build Command | {analysis.get('build_cmd') or 'auto'} |
| Test Command | {analysis.get('test_cmd') or 'none'} |
| Env Vars Needed | {len(env_vars)} |

## Pipeline Tasks

- [ ] 1. ANALYZE — Detect project type → {project_type} ({analysis['language']}, port {port})
- [ ] 2. SECRETS — Vault {len(env_vars)} env vars: {', '.join(env_vars[:5])}{'...' if len(env_vars) > 5 else ''}
- [ ] 3. DOCKERFILE — {'Validate existing' if has_dockerfile else 'Generate'} Dockerfile for {project_type}
- [ ] 4. BUILD — Push to GHCR: ghcr.io/executiveusa/{app_name}:latest
- [ ] 5. TEST — Container starts, /health returns 200
- [ ] 6. COOLIFY — Create/update application on Coolify Cloud
- [ ] 7. DATABASE — {'Provision PostgreSQL 16' if needs_db else 'Skip (not needed)'}
- [ ] 8. DEPLOY — Trigger deployment + monitor until finished
- [ ] 9. DNS — Configure {domain}
- [ ] 10. VERIFY — External health check with 5 retries
- [ ] 11. REPORT — Log results to memory

## Test Gates

| Step | Gate | Pass Criteria |
|------|------|---------------|
| 1 | Type Detection | project_type != "unknown" |
| 2 | Secrets Vault | All required env vars return values from vault_load |
| 3 | Dockerfile | File exists and is valid (docker build --check) |
| 4 | Build | GHCR image tag exists |
| 5 | Test | Container responds on port {port} |
| 6 | Coolify | App UUID returned from API |
| 7 | Database | {'Connection string valid' if needs_db else 'N/A (skip)'} |
| 8 | Deploy | deploy_status == "finished" |
| 9 | DNS | Domain resolves to 31.220.58.212 |
| 10 | Verify | HTTP 200 on /health AND / |
| 11 | Report | Summary saved to memory |

## Configuration

```yaml
app_name: {app_name}
repo_url: {repo_url}
branch: {branch}
type: {project_type}
port: {port}
domain: {domain}
needs_db: {str(needs_db).lower()}
has_dockerfile: {str(has_dockerfile).lower()}
env_vars: {env_vars}
```

## Progress Log

<!-- Appended by mark_task_done tool -->
"""

        # ── Step 3: Write PRD to workspace ───────────────────
        deploy_dir = PROJECT_ROOT / "workspace" / "deploys" / app_name
        deploy_dir.mkdir(parents=True, exist_ok=True)
        prd_path = deploy_dir / "PRD.md"
        prd_path.write_text(prd, encoding="utf-8")

        # Also write analysis as JSON for the loop engine
        import json
        config_path = deploy_dir / "config.json"
        config = {
            "app_name": app_name,
            "repo_url": repo_url,
            "branch": branch,
            "type": project_type,
            "language": analysis["language"],
            "port": port,
            "domain": domain,
            "needs_db": needs_db,
            "has_dockerfile": has_dockerfile,
            "env_vars_needed": env_vars,
            "build_cmd": analysis.get("build_cmd"),
            "test_cmd": analysis.get("test_cmd"),
            "start_cmd": analysis.get("start_cmd"),
        }
        config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

        return Response(
            message=f"PRD generated for '{app_name}' ({project_type}) at {prd_path}\n\n{prd}",
            break_loop=False,
        )
